repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      args: [--max-line-length=120]
    - id: trailing-whitespace
      exclude: "^.idea"
    - id: end-of-file-fixer
      exclude: "^.idea"
    - id: mixed-line-ending
      exclude: "^.idea"
      args: [--fix=lf]
